**NumPy** --by Punith V T

NumPy is a Python library used for working with arrays

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [28]:
import numpy as np

In [29]:
print(np.version)

<module 'numpy.version' from '/opt/conda/lib/python3.10/site-packages/numpy/version.py'>


**Creating Array**

In [30]:
#1D array
arr=np.array([1,2,3,4,5])
print(arr)

print(type(arr))

#2D array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [31]:
# Higher dimensional Array
arr = np.array([10, 20, 30, 40], ndmin=5)
print(arr)
print("number od dimension is:",arr.ndim)

[[[[[10 20 30 40]]]]]
number od dimension is: 5


**Array Slicing**

In [32]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr[1]) # by indexing 
print(arr[0:5])
print(arr[-6:-1])

2
[1 2 3 4 5]
[5 6 7 8 9]


**NumPy Function:**

insert() : insert values at a given place

In [33]:
a= np.insert(arr,0,100)
print(a)

[100   1   2   3   4   5   6   7   8   9   0]


In [34]:
#Numpy data types:
print(arr.dtype)

int64


**Copy:** Copy creates a new array, independent of the original, while view merely represents the original array. Copies are separate, preserving data isolation, while views share data, causing changes in one to impact the other

In [35]:
x = arr.copy()
arr[0] = 100

print(arr)
print(x)

[100   2   3   4   5   6   7   8   9   0]
[1 2 3 4 5 6 7 8 9 0]


**NumPy Array Iterating**

In [37]:
x=np.array([[1,2,3],[4,5,6]])
for i in x:
    print(i)

[1 2 3]
[4 5 6]


**Joining NumPy Arrays**

In [41]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
arr = np.concatenate((a1,a2))
arr

array([1, 2, 3, 4, 5, 6])

In [49]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])

# Stack arr1 and arr2 horizontally along the second axis (axis=1)
arr = np.stack((arr1, arr2), axis=1)

# Print the resulting array
print(arr)

[[10 40]
 [20 50]
 [30 60]]


**Splitting the array**

In [52]:
arr = np.array([1, 2, 3, 4, 5, 6])
new = np.array_split(arr, 3)
print(new)

[array([1, 2]), array([3, 4]), array([5, 6])]


**Searching Array**

In [54]:
arr = np.array([10, 20, 30, 40, 55, 45, 4])
x = np.where(arr == 5)
y = np.where(arr%2 == 0)
z = np.where(arr%2 == 1)
print(x)
print(y)
print(z)

(array([], dtype=int64),)
(array([0, 1, 2, 3, 6]),)
(array([4, 5]),)


**Sorting**

In [56]:
arr1= np.array([3, 2, 0, 1,-1])
arr2= np.array(['banana', 'cherry', 'apple',"orange"])

print(np.sort(arr2))
print(np.sort(arr1))

['apple' 'banana' 'cherry' 'orange']
[-1  0  1  2  3]


**Filter**

In [57]:
arr = np.array([41, 40, 42, 43, 44])

x = [True, True, False, True, False]

newarr = arr[x]

print(newarr)

[41 40 43]
